use_frameworks!

target 'libswift_Example' do
  pod 'libswift', :path => '../'
  pod 'Reveal-SDK', :configurations => ['Debug']
  target 'libswift_Tests' do
    inherit! :search_paths

#    pod 'Quick', '~> 0.8'
#    pod 'Nimble', '~> 3.0'
  end
end
